### ISSUE TITLE
Niedziałająca funkcja os.system('cls')?

### ISSUE THREAD

**Issue by shaunifire** [shaunifire/milionerzy_game#5]
W pliku Main_Code:

print ("Witam wszystkich serdecznie! Ja nazywam się Hubert Urbański, a to jest nasz dzisiejszy gość! Powiedz nam jak masz na imię?")
imie_gracza=input()
os.system('cls') #czy ktoś wie czemu wyskakuje mi cls not found?
print("Miło mi cię gościć", imie_gracza, " w naszym teleturnieju Milionerzy. Skąd jesteś?")
miasto_gracza=input()
os.system('cls')
print("To cudownie! Wszyscy cię dziś wspieramy. Czy jesteś gotów zgarnąć MILION ZŁOTYCH? Wciśnij ENTER aby rozpocząć!")
input()
#Tutaj muzyczka
os.system('cls')
print("Losujemy pierwsze pytanie!")

wydaje się, jakby os.system('cls') nie działał, wyskakuje sh:1 w konsoli zamiast działania. Anyone? Czy u was też nie działa?

**Comment by Elvarius** [comment]
import os
Jeśli używasz czegoś z biblioteki 'os' to musisz ją najpierw zaimportować ;) 
#Edit:
Nie zauważyłem, że chodzi ci o całokształt - zaraz ogarnę co i jak
#Edit2:
U mnie wszystko działa tak jak powinno, więc to u Ciebie musi być jakiś błąd :/

**Comment by shaunifire** [comment]
Good!
