### ISSUE TITLE
Niedziałająca pętla z time.sleep

### ISSUE THREAD

**Issue by shaunifire** [shaunifire/milionerzy_game#6]
#dlaczego poniższy kod mi nie działa? nie wypisuje elementów po sobie, tylko po odczekaniu 5 sekund wrzuca 5 kropek naraz
for i in range (0,5):
    print(".", end="")
    time.sleep(1)

**Comment by Elvarius** [comment]
End='' każe ciągle doklejać coś do istniejącego printa. Dlatego nie pokazuje po kolei pojawiających się kropek, a printuje od razu całość
#Edit: Jeśli usuniesz (, end="") to nadal to wygląda dobrze
Polecam robić także losowanie po każdym pytaniu, bo mi losowało tylko na pierwszym

**Comment by shaunifire** [comment]
Dzięki! poprawiam.
