### ISSUE TITLE
Test i poprawki muzyczki (branch kompilacja_kodu!)

### ISSUE THREAD

**Issue by shaunifire** [shaunifire/milionerzy_game#7]
@MPrzystalowski 
Twój kod został wcielony do kodu głównego, ale na moim branchu.
Potrzebuję pomocy z przetestowaniem działania muzyczki - nie wiem, czy kod poprawnie działa, bo nie mam zainstalowanego modułu i nie mam jak go zaimportować. 
Proszę też o dodanie treści w pliku ReadMe pod akapitem WYMAGANIA, bo trzeba dać informację kompletną o tym jak ustawić program i pliki żeby działały. 

Zmiany w kodzie wprowadź proszę tylko na moim branchu, żeby na masterze póki co kod był bez muzyczki. Dopiero kiedy będziemy pewni, że poprawnie działa - zmerge'ujemy go z masterem.

**Comment by shaunifire** [comment]
Hey @MPrzystalowski ! Zmerge'owałam kod z głównym, wiec jest teraz na MASTERZE. Wyskakuje mi, że nie moze znaleźć Czołóweczki.wav. Gdzie trzeba ją pobrać żeby odtworzył? Napisz proszę o tym w Readme.

**Comment by MPrzystalowski** [comment]
Done!

**Comment by MPrzystalowski** [comment]
Niepotrzebnie dodawałem poprawioną wersję. Jak ją usunąć żeby nie zawalała miejsca? :(

**Comment by shaunifire** [comment]
1. Znajdź elementy swojego kodu w Main_Code
2. Stwórz brancha z poprawką do Main_Code
3. Zrób pull reqest i zmerguj
4. Dodatkowy zbędny plik skasuj z mastera

Pamiętajmy, żeby robić ta procedurą, bo za to są punkciki. 
Zamknij issue, jak skończysz :) Wtedy będziemy mogli ruszyć dalej!

**Comment by MPrzystalowski** [comment]
Nie potrzebna jest poprawka do Main_code, po pobraniu "Czołóweczka.wav" i "Constant.wav" i usunięciu hashtagów w linijkach mojego kodu wszystko śmiga pięknie.
Plik "Czołóweczka poprawiona" jest niepotrzebny!
