### ISSUE TITLE
Niedziela rano - kompilacja kodu do .exe

### ISSUE THREAD

**Issue by shaunifire** [shaunifire/milionerzy_game#9]
Możemy zdobyć więcej punktów (nadrobić, jesli nam za coś odejmą) jeśli spakujemy cały program do działającego .exe. To nie jest takie trudne(sama zrobiłam to raz na kompie w szkole), ale ponieważ mam bieda-Kubuntu, nie mogę tego zrobić. 
Ktoś chce się wziąć? To jest dodatkowe zadanie, nie musimy tego robić.

**Comment by MPrzystalowski** [comment]
Czemu nie, zrobię to jak będziemy mieli full code!
